nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:3000', 'http://127.0.0.1:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': null
        '^/blog/': null
